### ISSUE TITLE
Frequency of USCIS Status Retrieval

### ISSUE THREAD

**Issue by xixihaha1995** [devidw/uscis#1]
Thank you for this helpful repository! Could you please let me know how often the system retrieves USCIS status updates?

**Comment by devidw** [comment]
Hey @xixihaha1995
I've deployed this on railway and the cron gets executed every hour
So you will get an email in the same hour as your case status changes

Edit: There was a bug with the email setup and with the persistence of the last check to figure out when to notify, fixed by now

**Comment by xixihaha1995** [comment]
Hello, devidw, about 7 hours ago, I recived email "Request for Additional Evidence Was Sent" from uscis@resend.wolf.gdn. Then, 41 minutes later, I received email "Case Is Being Actively Reviewed By USCIS" from uscis@resend.wolf.gdn, which is exactly the same from the official status website.

Is this some test you have done? Or actual status change from official USCIS website?

Thank you.

**Comment by devidw** [comment]
Ah sry for that, ignore the first mail. Must have been triggered by me when I fixed e900b34 and de3bdc0.
